CREATE DATABASE JSP_MVC2_EX2;
	
USE JSP_MVC2_EX2;

CREATE TABLE BOARD2 (
	BOARD_ID 	BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER 		VARCHAR(50),
    EMAIL 		VARCHAR(50),
    SUBJECT 	VARCHAR(50),
    PASSWORD 	VARCHAR(20),
    ENROLL_DT 	TIMESTAMP,
    READ_CNT 	BIGINT,
   	CONTENT 	VARCHAR(2000)
);

SELECT * FROM BOARD2;